export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const L_SELECTION_CHANGED = 'L_SELECTION_CHANGED';
export const R_SELECTION_CHANGED = 'R_SELECTION_CHANGED';
export const L_SEARCH_CHANGED = 'L_SEARCH_CHANGED';
export const R_SEARCH_CHANGED = 'R_SEARCH_CHANGED';
export const ASSIGN = 'ASSIGN';
export const UNASSIGN = 'UNASSIGN';
